---
abstract: 'Convert POD to Markdown'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Victor Moral <victor@taquiones.net>'
  - 'Ryan C. Thompson <rct at thompsonclan d0t org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Markdown
provides:
  Pod::Markdown:
    file: lib/Pod/Markdown.pm
    version: 1.103491
requires:
  Pod::Parser: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Markdown
  homepage: http://search.cpan.org/dist/Pod-Markdown/
  repository: git://github.com/hanekomu/Pod-Markdown.git
version: 1.103491
